/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    Avatar: typeof import('primevue/avatar')['default']
    AvatarGroup: typeof import('primevue/avatargroup')['default']
    Badge: typeof import('primevue/badge')['default']
    BowtieDiagram: typeof import('./components/diagram/BowtieDiagram.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Diagram: typeof import('./components/diagram/Diagram.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Editor: typeof import('primevue/editor')['default']
    Field: typeof import('./components/Field.vue')['default']
    Flex: typeof import('./components/Flex.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Panel: typeof import('primevue/panel')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    ResizableLayout: typeof import('./components/ResizableLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TreeTable: typeof import('primevue/treetable')['default']
    Zwutton: typeof import('./components/Zwutton.vue')['default']
  }
}
